<?php

$labels = array();

$labels['plugin_hotkeys'] = 'Plugin: Hot Keys';

$labels['hotkeys'] = 'Hot Keys';
$labels['activate_plugin'] = 'Activate plugin';
$labels['enable_logging'] = 'Enable plugin logging';
$labels['enable_button'] = 'Enable toolbar button';
$labels['enable_prevent'] = 'Prevent default browser keys';
$labels['plugin_hotkey'] = 'Plugin access key';
$labels['reset_to_default'] = 'Reset mappings to default';

$labels['button_text'] = 'Keys';
$labels['button_title'] = 'Configure keyboard shortcuts';

$labels['command_hotkeys'] = 'Command hotkeys';
$labels['command_mapping'] = 'Command mapping';

$labels['mapping'] = 'Mapping';

$labels['profile'] = 'Profile';
$labels['command'] = 'Command';
$labels['context'] = 'Context';
$labels['key'] = 'Key';
$labels['comment'] = 'Comment';
$labels['script'] = 'Script';
$labels['source'] = 'Source';

$labels['tooltip_profile'] = 'Profile which owns the command/key mapping';
$labels['tooltip_command'] = 'Command name for direct invocation';
$labels['tooltip_context'] = 'Select context filter for command application';
$labels['tooltip_key_enter'] = 'Enter shortcut name, i.e.: ctrl+f3';
$labels['tooltip_key_click'] = 'Click here, then press desired hot key';
$labels['tooltip_script'] = 'Optional javascript to override command-by-name';
$labels['tooltip_comment'] = 'Briefley describe operation performed by the command';

$labels['all'] = 'all';
$labels['active'] = 'active';
$labels['passive'] = 'passive';
$labels['custom'] = 'custom';
$labels['internal'] = 'internal';
$labels['external'] = 'external';
$labels['undefined'] = 'undefined';

$labels['apply'] = 'Apply';
$labels['update'] = 'Update';
$labels['create'] = 'Create';
$labels['remove'] = 'Remove';
$labels['invoke']  = 'Invoke';
$labels['close'] = 'Close';

$labels['new'] = 'New';
$labels['change'] = 'Change';
$labels['export'] = 'Export';
$labels['import'] = 'Import';
$labels['share'] = 'Share';

$labels['combine'] = 'Combine';

$labels['import_mapping'] = 'Import command hotkeys';
$labels['export_mapping'] = 'Export command hotkeys';
$labels['share_mapping'] = 'Share command hotkeys';
$labels['share_via_imap'] = 'Public mailbox';
$labels['share_via_mail'] = 'Send attachment';

$labels['success'] = 'Success';
$labels['failure'] = 'Failure';

$labels['profile_list'] = 'Profile list';

$labels['custom_command_list'] = 'Custom command list';
$labels['internal_command_list'] = 'Internal command list';
$labels['supported_base_keys'] = 'Supported base keys';
$labels['supported_meta_keys'] = 'Supported meta keys';
$labels['prevent_default_keys'] = 'Prevented browser keys list';

?>
